name: agent-api
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12

  - jinja2=3.1

  - fastapi=0.112
  - fastapi-cli
  - pydantic=2.8

  - psycopg=3.2
  - sqlalchemy=2.0

  - openai=1.52

  - backoff[version='>=1.10.0']
  - wrapt[version='<2.0,>=1.14']
  - packaging[version='<25.0,>=23.2']
  - pip:
    - langfuse==2.53
